### ISSUE TITLE
跑quick start遇到问题 python run_model.py --task traffic_state_pred --model GRU --dataset METR_LA --gpu False

### ISSUE THREAD

**Issue by davechenxy** [LibCity/Bigscity-LibCity-Docs-zh_CN#6]
1. 第一个错是让我装mxnet, 不知道没有包含在requirements里
2. 第二个是跑quick start命令报错: File “/Bigscity-LibCity-master/libcity/model/traffic_speed_prediction/STMGAT.py", line 3, in <module>
    from dgl.nn.pytorch.conv import GATConv
ModuleNotFoundError: No module named 'dgl.nn.pytorch'

**Comment by aptx1231** [comment]
我们不依赖与mxnet，所以应该不会报这个错误的，能否提供截图？
第二个错误请确认是否安装了dgl库呢？
推荐您到我们的[代码仓库](https://github.com/LibCity/Bigscity-LibCity)提ISSUE哦！

**Comment by davechenxy** [comment]
对，所以我也有点奇怪报了mxnet的错误，不过这个不是很重要；

第二是装了dgl的，后来改成了“from dgl.nn import GATConv” 就可以了

**Comment by aptx1231** [comment]
这应该是dgl依赖版本不对的原因，

**Comment by davechenxy** [comment]
Traceback (most recent call last):
  File "/home/xiangyu/gd/Bigscity-LibCity-master/libcity/utils/utils.py", line 48, in get_model
    return getattr(importlib.import_module('libcity.model.traffic_flow_prediction'),
AttributeError: module 'libcity.model.traffic_flow_prediction' has no attribute 'RNN'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_model.py", line 36, in <module>
    run_model(task=args.task, model_name=args.model, dataset_name=args.dataset,
  File "/home/xiangyu/gd/Bigscity-LibCity-master/libcity/pipeline/pipeline.py", line 53, in run_model
    model = get_model(config, data_feature)
  File "/home/xiangyu/gd/Bigscity-LibCity-master/libcity/utils/utils.py", line 52, in get_model
    return getattr(importlib.import_module('libcity.model.traffic_speed_prediction'),
  File "/home/xiangyu/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/xiangyu/gd/Bigscity-LibCity-master/libcity/model/traffic_speed_prediction/__init__.py", line 16, in <module>
    from libcity.model.traffic_speed_prediction.STMGAT import STMGAT
  File "/home/xiangyu/gd/Bigscity-LibCity-master/libcity/model/traffic_speed_prediction/STMGAT.py", line 2, in <module>
    from dgl.nn.pytorch import GATConv
  File "/home/xiangyu/anaconda3/lib/python3.8/site-packages/dgl/__init__.py", line 13, in <module>
    from .backend import load_backend, backend_name
  File "/home/xiangyu/anaconda3/lib/python3.8/site-packages/dgl/backend/__init__.py", line 95, in <module>
    load_backend(get_preferred_backend())
  File "/home/xiangyu/anaconda3/lib/python3.8/site-packages/dgl/backend/__init__.py", line 33, in load_backend
    import mxnet
ModuleNotFoundError: No module named 'mxnet'

**Comment by davechenxy** [comment]
好的，下次我去主代码仓库下提问

**Comment by davechenxy** [comment]
>>> import dgl
Using backend: mxnet

嗯嗯，可能我以前用过dgl，所以跑requirements的时候他是不是就不会自动替换版本，导致用了不同版本的dgl

**Comment by davechenxy** [comment]
>>> import dgl
Using backend: mxnet
>>> dgl.__version__
'0.6.1'

嗯嗯，可能我以前用过dgl，所以跑requirements的时候他是不是就不会自动替换版本，导致用了不同版本的dgl

**Comment by aptx1231** [comment]
好的，我不太了解dgl这个库是怎么识别pytorch和mxnet的，可能你把这两个框架安装在同一个虚拟环境里边了。
另外dgl这个库在libcity中应用不多，只有STMGAT模型用到了，如果不需要这个模型的话，可以把这个文件删掉，记得修改对应文件夹下的init.py即可。

**Comment by davechenxy** [comment]
> 
好的， 感谢回复
